routes/web.php
<?php

use App\Http\Controllers\BackendHelperController;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['auth'],'prefix'=>'admin'], function (){
    Route::get('/dashboard', function () {
        $coursesCount = \App\Models\Courses::count();
        $CertificateCount = \App\Models\Certificate::count();
        $InstructorCount = \App\Models\Instructor::count();
        return view('dashboard.dashboard.index',compact('coursesCount','CertificateCount','InstructorCount'));
    })->middleware(['auth'])->name('dashboard');

    Route::resource('news',\App\Http\Controllers\NewsController::class);
    Route::resource('certificates',\App\Http\Controllers\CertificateController::class);
    Route::resource('departments',\App\Http\Controllers\DepartmentController::class)->except('show');
    Route::resource('accreditCenter',\App\Http\Controllers\AccreditCenterController::class)->except('show');
    Route::resource('courses',\App\Http\Controllers\CoursesController::class);
    Route::get('setting',[\App\Http\Controllers\SettingsController::class,'index'])->name('settings.index');
    Route::post('setting',[\App\Http\Controllers\SettingsController::class,'update'])->name('settings.update');
    Route::post('setting',[\App\Http\Controllers\SettingsController::class,'update'])->name('settings.update');
//    Route::resource('instructor',\App\Http\Controllers\InstructorController::class);
    Route::resource('chats',\App\Http\Controllers\ChatController::class);
    Route::resource('branches',\App\Http\Controllers\BranchesController::class);

    Route::prefix('upload')->name('upload.')->group(function(){
        Route::post('/image',[BackendHelperController::class,'upload_image'])->name('image');
        Route::post('/file',[BackendHelperController::class,'upload_file'])->name('file');
        Route::post('/remove-file',[BackendHelperController::class,'remove_files'])->name('remove-file');
    });

});

Route::get('/', [\App\Http\Controllers\FrontController::class,'index'])->name('home');
Route::get('department/{department}',[\App\Http\Controllers\FrontController::class,'showDep'])->name('department.show');
Route::get('search',[\App\Http\Controllers\FrontController::class,'search'])->name("search");



Route::get('robots.txt',[\App\Http\Controllers\HelperController::class,'robots']);
//Route::get('manifest.json',[HelperController::class,'manifest']);
Route::get('sitemap.xml',[\App\Http\Controllers\SiteMapController::class,'sitemap']);


Route::get('instructors',[\App\Http\Controllers\FrontController::class,'instructors'])->name('instructors');
Route::get('instructors/{instructor}',[\App\Http\Controllers\FrontController::class,'instructorsShow'])->name('instructors.show');

Route::get('explore/{course}',[\App\Http\Controllers\FrontController::class,'showCourse'])->name('course.show');
Route::get('contact-us',[\App\Http\Controllers\FrontController::class,'contactUs'])->name('contact.us');
Route::get('about-us',[\App\Http\Controllers\FrontController::class,'aboutUs'])->name('about.us');
Route::get('branches',[\App\Http\Controllers\FrontController::class,'branches'])->name('branches');
Route::get('centers',[\App\Http\Controllers\FrontController::class,'centers'])->name('centers');
Route::get('blog/news',[\App\Http\Controllers\FrontController::class,'news'])->name('front.news');
Route::get('blog/news/{news}',[\App\Http\Controllers\FrontController::class,'newsShow'])->name('front.news.show');


Route::get('certificate/verify/{uuid?}',[\App\Http\Controllers\FrontController::class,'certificate_verify'])->name('front.certificate.verify');
Route::get('certificate/show/{uuid?}',[\App\Http\Controllers\FrontController::class,'certificate_show'])->name('front.certificate.show');


Route::post('/contact-us-form',[\App\Http\Controllers\FrontController::class,'submitContactUs'])->name('submitContactUs');
require __DIR__.'/auth.php';


Route::get('/cccc',function (){

    $certificates = \App\Models\Certificate::all();

    foreach ($certificates as $certificate){
        $uuid = Str::uuid()->toString();
        $certificate->update([
            'uuid' => $uuid,
        ]);
    }


//    $depars = \App\Models\Department::all();
//    foreach ($depars as $dep){
//        $c = json_decode($dep->courses,true);
//
//        foreach ($c['names'] as $index => $name){
//            $desc = $c['desc'][$index];
//            $course = \App\Models\Courses::create([
//                'name' => $name,
//                'info' => $desc,
//                'location' => ' ',
//                'dep_id' => $dep->id,
//                'price' => null,
//                'start_date' => null,
//                'cover' => '1670360646UK1.jpg',
//                'icon' => '',
//                'status' => 0,
//            ]);
//        }
//    }

});

app/Models/Chat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Chat extends Model
{
    use HasFactory;

    protected $fillable = [
        'question',
        'answer'
    ];
}

app/Http/Controllers/ChatController.php
<?php

namespace App\Http\Controllers;

use App\Models\Chat;
use Illuminate\Http\Request;

class ChatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $chats = Chat::paginate();
        return view('dashboard.chat.index',compact('chats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.chat.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'question' => 'required|string',
            'answer' => 'required|string',
        ]);

        Chat::create([
            'question' => $request->get('question'),
            'answer' => $request->get('answer'),
        ]);

        return redirect()->route('chats.index')->with('success','Chat added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Chat  $chat
     * @return \Illuminate\Http\Response
     */
    public function show(Chat $chat)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Chat  $chat
     * @return \Illuminate\Http\Response
     */
    public function edit(Chat $chat)
    {
        return view('dashboard.chat.edit',compact('chat'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Chat  $chat
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Chat $chat)
    {
        $this->validate($request,[
            'question' => 'required|string',
            'answer' => 'required|string',
        ]);

        $chat->fill([
            'question' => $request->get('question'),
            'answer' => $request->get('answer'),
        ])->save();

        return redirect()->route('chats.index')->with('success','Chat Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Chat  $chat
     * @return \Illuminate\Http\Response
     */
    public function destroy(Chat $chat)
    {
        $chat->delete();
        return redirect()->route('chats.index')->with('success','Chat Deleted Successfully');
    }
}

resources/views/dashboard/chat/create.blade.php
@extends('layouts.app')

@section('content')


    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header pb-0">
                    <div class="d-flex align-items-center">
                        <p class="mb-0">Add New Chat</p>

                    </div>
                </div>
                <div class="card-body">
                    <form action="{{route('chats.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="example-text-input" class="form-control-label">question</label>
                                <input class="form-control" type="text" name="question" value="{{old('question')}}" onfocus="focused(this)" onfocusout="defocused(this)">
                                @if($errors->has('question'))
                                    <span class="text-danger text-gradient px-3 mb-0"> {{ $errors->first('question') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="example-text-input" class="form-control-label">Answer</label>
                                <textarea  class="form-control"  name="answer" >{{old('answer')}}</textarea>
                                @if($errors->has('answer'))
                                    <span class="text-danger text-gradient "> {{ $errors->first('answer') }}</span>
                                @endif
                            </div>
                        </div>




                        <div class="col-md-6">
                            <div class="form-group">
                               <button type="submit" class="btn btn-primary">Add</button>
                            </div>
                        </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>

    </div>



@endsection

resources/views/dashboard/chat/edit.blade.php
@extends('layouts.app')

@section('content')


    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header pb-0">
                    <div class="d-flex align-items-center">
                        <p class="mb-0">Edit chat</p>

                    </div>
                </div>
                <div class="card-body">
                    <form action="{{route('chats.update',['chat'=>$chat->id])}}" method="post"
                          enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="example-text-input" class="form-control-label">question</label>
                                    <input class="form-control" type="text" name="question" value="{{$chat->question}}"
                                           onfocus="focused(this)" onfocusout="defocused(this)">
                                    @if($errors->has('question'))
                                        <span
                                            class="text-danger text-gradient px-3 mb-0"> {{ $errors->first('question') }}</span>
                                    @endif
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="example-text-input" class="form-control-label">Answer</label>
                                    <textarea class="form-control" name="answer"
                                             >{{$chat->answer}}</textarea>
                                    @if($errors->has('answer'))
                                        <span class="text-danger text-gradient "> {{ $errors->first('answer') }}</span>
                                    @endif
                                </div>
                            </div>


                            <div class="col-md-6">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>



@endsection

resources/views/dashboard/chat/index.blade.php
@extends('layouts.app')

@section('content')



    <div class="row">
        <div class="col-12">
            <div class="card mb-4">

                <div class="card-header pb-0">
                    <h6>Chats</h6>
                    <a href="{{route('chats.create')}}" class="btn btn-primary btn-sm ms-auto"> Add </a>
                </div>
                @include('dashboard.shared.alerts')
                <div class="card-body px-0 pt-0 pb-2">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center mb-0">
                            <thead>
                            <tr>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Question
                                </th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                    Answer
                                </th>



                                <th class="text-secondary opacity-7"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($chats as $chat)

                                <tr>
                                    <td style="overflow: hidden;max-width: 100px;">
                                        <div class="d-flex px-2 py-1">

                                            <div class="d-flex flex-column justify-content-center">
                                                <h6 class="mb-0 text-sm">{{$chat->question}}</h6>

                                            </div>
                                        </div>
                                    </td>
                                    <td style="overflow: hidden;max-width: 100px;">
                                        <p class="text-xs font-weight-bold mb-0">{{$chat->answer}}</p>

                                    </td>
                                    <td class="align-middle">
                                        <form action="{{route('chats.destroy',['chat'=>$chat->id])}}"
                                              id="delete_{{$chat->id}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{route('chats.edit',['chat'=>$chat->id])}}"
                                               class=" text-success  font-weight-bold text-xs">
                                                <i class="fa-solid fa-pen-alt me-2" aria-hidden="true"></i>
                                                Edit
                                            </a>
                                            <a href="javascript:deleteForm('delete_{{$chat->id}}');"
                                               class=" text-warning  font-weight-bold text-xs">
                                                <i class="fa-solid fa-trash-alt ms-2" aria-hidden="true"></i>
                                                Delete
                                            </a>

                                        </form>
                                    </td>

                                </tr>



                            @empty
                                <tr>

                                    <td>
                                        <p class="text-xs font-weight-bold mb-0">No Data</p>

                                    </td>


                                </tr>

                            @endforelse

                            </tbody>
                        </table>

                        <div class="text-center m-3">
                            {{$chats->links()}}
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>



@endsection