routes/web.php
<?php

use App\Http\Controllers\BackendHelperController;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['auth'],'prefix'=>'admin'], function (){
    Route::get('/dashboard', function () {
        $coursesCount = \App\Models\Courses::count();
        $CertificateCount = \App\Models\Certificate::count();
        $InstructorCount = \App\Models\Instructor::count();
        return view('dashboard.dashboard.index',compact('coursesCount','CertificateCount','InstructorCount'));
    })->middleware(['auth'])->name('dashboard');

    Route::resource('news',\App\Http\Controllers\NewsController::class);
    Route::resource('certificates',\App\Http\Controllers\CertificateController::class);
    Route::resource('departments',\App\Http\Controllers\DepartmentController::class)->except('show');
    Route::resource('accreditCenter',\App\Http\Controllers\AccreditCenterController::class)->except('show');
    Route::resource('courses',\App\Http\Controllers\CoursesController::class);
    Route::get('setting',[\App\Http\Controllers\SettingsController::class,'index'])->name('settings.index');
    Route::post('setting',[\App\Http\Controllers\SettingsController::class,'update'])->name('settings.update');
    Route::post('setting',[\App\Http\Controllers\SettingsController::class,'update'])->name('settings.update');
//    Route::resource('instructor',\App\Http\Controllers\InstructorController::class);
    Route::resource('chats',\App\Http\Controllers\ChatController::class);
    Route::resource('branches',\App\Http\Controllers\BranchesController::class);

    Route::prefix('upload')->name('upload.')->group(function(){
        Route::post('/image',[BackendHelperController::class,'upload_image'])->name('image');
        Route::post('/file',[BackendHelperController::class,'upload_file'])->name('file');
        Route::post('/remove-file',[BackendHelperController::class,'remove_files'])->name('remove-file');
    });

});

Route::get('/', [\App\Http\Controllers\FrontController::class,'index'])->name('home');
Route::get('department/{department}',[\App\Http\Controllers\FrontController::class,'showDep'])->name('department.show');
Route::get('search',[\App\Http\Controllers\FrontController::class,'search'])->name("search");



Route::get('robots.txt',[\App\Http\Controllers\HelperController::class,'robots']);
//Route::get('manifest.json',[HelperController::class,'manifest']);
Route::get('sitemap.xml',[\App\Http\Controllers\SiteMapController::class,'sitemap']);


Route::get('instructors',[\App\Http\Controllers\FrontController::class,'instructors'])->name('instructors');
Route::get('instructors/{instructor}',[\App\Http\Controllers\FrontController::class,'instructorsShow'])->name('instructors.show');

Route::get('explore/{course}',[\App\Http\Controllers\FrontController::class,'showCourse'])->name('course.show');
Route::get('contact-us',[\App\Http\Controllers\FrontController::class,'contactUs'])->name('contact.us');
Route::get('about-us',[\App\Http\Controllers\FrontController::class,'aboutUs'])->name('about.us');
Route::get('branches',[\App\Http\Controllers\FrontController::class,'branches'])->name('branches');
Route::get('centers',[\App\Http\Controllers\FrontController::class,'centers'])->name('centers');
Route::get('blog/news',[\App\Http\Controllers\FrontController::class,'news'])->name('front.news');
Route::get('blog/news/{news}',[\App\Http\Controllers\FrontController::class,'newsShow'])->name('front.news.show');


Route::get('certificate/verify/{uuid?}',[\App\Http\Controllers\FrontController::class,'certificate_verify'])->name('front.certificate.verify');
Route::get('certificate/show/{uuid?}',[\App\Http\Controllers\FrontController::class,'certificate_show'])->name('front.certificate.show');


Route::post('/contact-us-form',[\App\Http\Controllers\FrontController::class,'submitContactUs'])->name('submitContactUs');
require __DIR__.'/auth.php';


Route::get('/cccc',function (){

    $certificates = \App\Models\Certificate::all();

    foreach ($certificates as $certificate){
        $uuid = Str::uuid()->toString();
        $certificate->update([
            'uuid' => $uuid,
        ]);
    }


//    $depars = \App\Models\Department::all();
//    foreach ($depars as $dep){
//        $c = json_decode($dep->courses,true);
//
//        foreach ($c['names'] as $index => $name){
//            $desc = $c['desc'][$index];
//            $course = \App\Models\Courses::create([
//                'name' => $name,
//                'info' => $desc,
//                'location' => ' ',
//                'dep_id' => $dep->id,
//                'price' => null,
//                'start_date' => null,
//                'cover' => '1670360646UK1.jpg',
//                'icon' => '',
//                'status' => 0,
//            ]);
//        }
//    }

});

app/Models/Certificate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Session\Store;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

class Certificate extends Model
{
    use HasFactory;

    protected $fillable = [
        'cert_id',
        'info',
        'uuid',
        'file'
    ];


    public function getFileAttribute()
    {

        $url = env("STORAGE_URL") . "/uploads/certificates/" . $this->attributes['file'];
        if (Storage::disk('public')->exists("/public/uploads/certificates/" . $this->attributes['file'])) {

            $file = Storage::disk('public')->get("/public/uploads/certificates/" . $this->attributes['file']);

            $pdf = base64_encode($file);

            return $pdf;
        }


        return null;

    }

    public function getFilePathAttribute()
    {

        $url = env("STORAGE_URL") . "/uploads/certificates/" . $this->attributes['file'];
        return $url;
        if (Storage::disk('public')->exists("/public/uploads/certificates/" . $this->attributes['file'])) {

            $file = Storage::disk('public')->get("/public/uploads/certificates/" . $this->attributes['file']);

            $pdf = base64_encode($file);

            return $pdf;
        }


        return null;

    }
}

app/Http/Controllers/CertificateController.php
<?php

namespace App\Http\Controllers;

use App\Models\Certificate;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class CertificateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $certificate = Certificate::paginate();
        return view('dashboard.certificate.index', compact('certificate'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.certificate.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'cert_id' => 'required|unique:certificates',
            'info' => 'nullable|string',
            'file' => 'required|file|mimetypes:application/pdf|max:1024',
        ]);



        $certificate = Certificate::create([
            'cert_id' => $request->get('cert_id'),
            'info' => $request->get('info'),
            'uuid' => Str::uuid()->toString(),
            'file' => '',
        ]);

        if ($request->hasFile('file')) {
            $file = $this->store_file([
                'source' => $request['file'],
                'validation' => "image",
                'path_to_save' => '/uploads/certificates/',
                'type' => 'PDF',
                'user_id' => Auth::user()->id,
                //'resize'=>[500,1000],
                'small_path' => 'small/',
                'visibility' => 'PUBLIC',
                'file_system_type' => env('FILESYSTEM_DRIVER', 'public'),
                'optimize' => false
            ])['filename'];
            $certificate->update([
                'file' => $file,
            ]);
        }
        return redirect()->route('certificates.index')->with('success', 'Certificate added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Certificate $certificate
     * @return \Illuminate\Http\Response
     */
    public function show(Certificate $certificate)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Certificate $certificate
     * @return \Illuminate\Http\Response
     */
    public function edit(Certificate $certificate)
    {
        return view('dashboard.certificate.edit', compact('certificate'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Certificate $certificate
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Certificate $certificate)
    {
        $this->validate($request, [
            'cert_id' => 'required|unique:certificates,cert_id,' . $certificate->id,
            'info' => 'nullable|string',
            'file' => 'nullable|file|mimetypes:application/pdf|max:1024',
        ]);

        $certificate->fill([
            'cert_id' => $request->get('cert_id'),
            'info' => $request->get('info'),
        ])->save();


        if ($request->hasFile('file')) {
            if(Storage::disk('public')->exists("/public/uploads/certificates/" .  $certificate->getAttributes()['file'])){

                $file = Storage::disk('public')->delete("/public/uploads/certificates/" .  $certificate->getAttributes()['file']);

            }

            $file = $this->store_file([
                'source' => $request['file'],
                'validation' => "image",
                'path_to_save' => '/uploads/certificates/',
                'type' => 'PDF',
                'user_id' => Auth::user()->id,
                //'resize'=>[500,1000],
                'small_path' => 'small/',
                'visibility' => 'PUBLIC',
                'file_system_type' => env('FILESYSTEM_DRIVER', 'public'),
                'optimize' => false
            ])['filename'];
            $certificate->update([
                'file' => $file,
            ]);
        }

        return redirect()->route('certificates.index')->with('success', 'Certificate Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Certificate $certificate
     * @return \Illuminate\Http\Response
     */
    public function destroy(Certificate $certificate)
    {

        if(Storage::disk('public')->exists("/public/uploads/certificates/" . $certificate->getAttributes()['file'])){

            $file = Storage::disk('public')->delete("/public/uploads/certificates/" . $certificate->getAttributes()['file']);

        }
        $certificate->delete();

        return redirect()->route('certificates.index')->with('success', 'Certificate Deleted Successfully');


    }

    public function check_certificate(Request $request)
    {

        $this->validate($request, [
            'cert_id' => 'required',
        ]);
        $cert_id = $request->get('cert_id');
        $cert = Certificate::all()->where('cert_id', $cert_id)->first();
        //print_r($cert);
        if ($cert) {
            return  redirect()->route('front.certificate.verify',$cert->uuid);
            return response()->json([
                'data' => [
                    'status' => true,
                    'info' => $cert->info,
                    'msg' => 'This certificate is valid'
                ]
            ], 200);
        }
        return  redirect()->route('front.certificate.verify',null);
        return response()->json([
            'data' => [
                'status' => false,
                'msg' => 'This certificate is not valid'
            ]
        ], 200);

    }
}

resources/views/dashboard/certificate/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header pb-0">
                    <div class="d-flex align-items-center">
                        <p class="mb-0">Add New Certificate</p>

                    </div>
                </div>
                <div class="card-body">
                    <form action="{{route('certificates.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="example-text-input" class="form-control-label">Certificate ID</label>
                                    <input class="form-control" type="text" name="cert_id" value="{{old('cert_id')}}"

                                    >
                                    @error('cert_id')
                                    <span
                                        class="text-danger text-gradient px-3 mb-0"> {{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="example-text-input" class="form-control-label">Certificate File</label>
                                    <input class="form-control" type="file" accept="application/pdf" name="file"
                                           required>
                                    @error('file')

                                    <span
                                        class="text-danger  text-gradient px-3 mb-0"> {{$message }}</span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="example-text-input" class="form-control-label">Info</label>
                                    <textarea class="editor" name="info">{{old('info')}}</textarea>
                                    @error('info')

                                    <span
                                        class="text-danger  text-gradient px-3 mb-0"> {{$message }}</span>
                                    @enderror

                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">Add</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

@endsection

resources/views/dashboard/certificate/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header pb-0">
                    <div class="d-flex align-items-center">
                        <p class="mb-0">Edit Certificate</p>

                    </div>
                </div>
                <div class="card-body">
                    <form action="{{route('certificates.update',['certificate'=>$certificate->id])}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="example-text-input" class="form-control-label">Certificate ID</label>
                                    <input class="form-control" type="text" name="cert_id"
                                           value="{{$certificate->cert_id}}"
                                           onfocus="focused(this)" onfocusout="defocused(this)">
                                    @if($errors->has('cert_id'))
                                        <span
                                            class="text-danger text-gradient px-3 mb-0"> {{ $errors->first('cert_id') }}</span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="example-text-input" class="form-control-label">Certificate File</label>
                                    <input class="form-control" type="file" accept="application/pdf" name="file"
                                           required>
                                    <small>Dont upload new one if you not need to update it</small>
                                    @error('file')

                                    <span
                                        class="text-danger  text-gradient px-3 mb-0"> {{$message }}</span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="example-text-input" class="form-control-label">Info</label>
                                    <textarea class="form-control editor" name="info"
                                    >{{$certificate->info}}</textarea>
                                    @if($errors->has('info'))
                                        <span class="text-danger text-gradient "> {{ $errors->first('info') }}</span>
                                    @endif
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">Add</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

@endsection

resources/views/dashboard/certificate/index.blade.php
@extends('layouts.app')

@section('content')



    <div class="row">
        <div class="col-12">
            <div class="card mb-4">

                <div class="card-header pb-0">
                    <h6>Certificates</h6>
                    <a href="{{route('certificates.create')}}" class="btn btn-primary btn-sm ms-auto"> Add </a>
                </div>
                @include('dashboard.shared.alerts')
                <div class="card-body px-0 pt-0 pb-2">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center mb-0">
                            <thead>
                            <tr>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">ID
                                </th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                    Info
                                </th>

                                <th class="text-secondary opacity-7"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($certificate as $cert)

                                <tr>
                                    <td>
                                        <div class="d-flex px-2 py-1">

                                            <div class="d-flex flex-column justify-content-center">
                                                <h6 class="mb-0 text-sm">{{$cert->cert_id}}</h6>

                                            </div>
                                        </div>
                                    </td>
                                    <td style="overflow: hidden;max-width: 100px;">
                                        <p class="text-xs font-weight-bold mb-0">{!! $cert->info!!}</p>
                                    </td>
                                    <td class="align-middle">
                                        <form action="{{route('certificates.destroy',['certificate'=>$cert->id])}}"
                                              id="delete_{{$cert->id}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <a href="javascript:deleteForm('delete_{{$cert->id}}');"
                                               class=" text-warning  font-weight-bold text-xs">
                                                <i class="fa-solid fa-trash-alt me-2" aria-hidden="true"></i>
                                                Delete
                                            </a>

                                            <a href="{{route('certificates.edit',['certificate'=>$cert->id])}}"
                                               class=" text-success  font-weight-bold text-xs">
                                                <i class="fa-solid fa-pen-alt me-2" aria-hidden="true"></i>
                                                Edit
                                            </a>
                                        </form>
                                    </td>

                                </tr>



                            @empty
                                <tr>

                                    <td>
                                        <p class="text-xs font-weight-bold mb-0">No Data</p>

                                    </td>


                                </tr>

                            @endforelse

                            </tbody>
                        </table>

                        <div class="text-center m-3">
                            {{$certificate->links()}}
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>



@endsection