routes/web.php
<?php

use App\Http\Controllers\BackendHelperController;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['auth'],'prefix'=>'admin'], function (){
    Route::get('/dashboard', function () {
        $coursesCount = \App\Models\Courses::count();
        $CertificateCount = \App\Models\Certificate::count();
        $InstructorCount = \App\Models\Instructor::count();
        return view('dashboard.dashboard.index',compact('coursesCount','CertificateCount','InstructorCount'));
    })->middleware(['auth'])->name('dashboard');

    Route::resource('news',\App\Http\Controllers\NewsController::class);
    Route::resource('certificates',\App\Http\Controllers\CertificateController::class);
    Route::resource('departments',\App\Http\Controllers\DepartmentController::class)->except('show');
    Route::resource('accreditCenter',\App\Http\Controllers\AccreditCenterController::class)->except('show');
    Route::resource('courses',\App\Http\Controllers\CoursesController::class);
    Route::get('setting',[\App\Http\Controllers\SettingsController::class,'index'])->name('settings.index');
    Route::post('setting',[\App\Http\Controllers\SettingsController::class,'update'])->name('settings.update');
    Route::post('setting',[\App\Http\Controllers\SettingsController::class,'update'])->name('settings.update');
//    Route::resource('instructor',\App\Http\Controllers\InstructorController::class);
    Route::resource('chats',\App\Http\Controllers\ChatController::class);
    Route::resource('branches',\App\Http\Controllers\BranchesController::class);

    Route::prefix('upload')->name('upload.')->group(function(){
        Route::post('/image',[BackendHelperController::class,'upload_image'])->name('image');
        Route::post('/file',[BackendHelperController::class,'upload_file'])->name('file');
        Route::post('/remove-file',[BackendHelperController::class,'remove_files'])->name('remove-file');
    });

});

Route::get('/', [\App\Http\Controllers\FrontController::class,'index'])->name('home');
Route::get('department/{department}',[\App\Http\Controllers\FrontController::class,'showDep'])->name('department.show');
Route::get('search',[\App\Http\Controllers\FrontController::class,'search'])->name("search");



Route::get('robots.txt',[\App\Http\Controllers\HelperController::class,'robots']);
//Route::get('manifest.json',[HelperController::class,'manifest']);
Route::get('sitemap.xml',[\App\Http\Controllers\SiteMapController::class,'sitemap']);


Route::get('instructors',[\App\Http\Controllers\FrontController::class,'instructors'])->name('instructors');
Route::get('instructors/{instructor}',[\App\Http\Controllers\FrontController::class,'instructorsShow'])->name('instructors.show');

Route::get('explore/{course}',[\App\Http\Controllers\FrontController::class,'showCourse'])->name('course.show');
Route::get('contact-us',[\App\Http\Controllers\FrontController::class,'contactUs'])->name('contact.us');
Route::get('about-us',[\App\Http\Controllers\FrontController::class,'aboutUs'])->name('about.us');
Route::get('branches',[\App\Http\Controllers\FrontController::class,'branches'])->name('branches');
Route::get('centers',[\App\Http\Controllers\FrontController::class,'centers'])->name('centers');
Route::get('blog/news',[\App\Http\Controllers\FrontController::class,'news'])->name('front.news');
Route::get('blog/news/{news}',[\App\Http\Controllers\FrontController::class,'newsShow'])->name('front.news.show');


Route::get('certificate/verify/{uuid?}',[\App\Http\Controllers\FrontController::class,'certificate_verify'])->name('front.certificate.verify');
Route::get('certificate/show/{uuid?}',[\App\Http\Controllers\FrontController::class,'certificate_show'])->name('front.certificate.show');


Route::post('/contact-us-form',[\App\Http\Controllers\FrontController::class,'submitContactUs'])->name('submitContactUs');
require __DIR__.'/auth.php';


Route::get('/cccc',function (){

    $certificates = \App\Models\Certificate::all();

    foreach ($certificates as $certificate){
        $uuid = Str::uuid()->toString();
        $certificate->update([
            'uuid' => $uuid,
        ]);
    }


//    $depars = \App\Models\Department::all();
//    foreach ($depars as $dep){
//        $c = json_decode($dep->courses,true);
//
//        foreach ($c['names'] as $index => $name){
//            $desc = $c['desc'][$index];
//            $course = \App\Models\Courses::create([
//                'name' => $name,
//                'info' => $desc,
//                'location' => ' ',
//                'dep_id' => $dep->id,
//                'price' => null,
//                'start_date' => null,
//                'cover' => '1670360646UK1.jpg',
//                'icon' => '',
//                'status' => 0,
//            ]);
//        }
//    }

});

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class News extends Model
{
    use HasFactory;

    protected $fillable = [
        'title', 'body', 'cover', 'slug'
    ];


// Carbon instance fields
    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    public function getCoverAttribute()
    {
        ;
        return $this->attributes['cover'] ?
            env("STORAGE_URL") . "/uploads/news/" . $this->attributes['cover']
            : asset('img/header-img.webp');
    }

    public function getShortTitleAttribute()
    {
        return \Illuminate\Support\Str::limit(trim(preg_replace('/\s\s+/', ' ', strip_tags($this->body))), 100, $end = '...');
    }

}

app/Http/Controllers/FrontController.php
<?php

namespace App\Http\Controllers;

use App\Mail\ContactUs;
use App\Mail\ContactUsAdmin;
use App\Models\AccreditCenter;
use App\Models\Branches;
use App\Models\Certificate;
use App\Models\Chat;
use App\Models\Courses;
use App\Models\Department;
use App\Models\Instructor;
use App\Models\News;
use App\Models\settings;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\View;

class FrontController extends Controller
{

    public function __construct()
    {

        $siteDescription = settings::get('site_desc');
        $siteKeywords = settings::get('site_keywords');
        $whatsappNumber = settings::get('whatsapp_number');
        $contactEmail = settings::get('contact_email');
        $contactPhone = settings::get('contact_phone');
        $siteType = settings::get('site_type');

        $siteInsta = settings::get('instagram');
        $siteFacebook = settings::get('facebook');

        $siteLinkedName = settings::get('LinkedinName');
        $siteLinked = settings::get('Linkedin');

        $siteInstaName = settings::get('instagramName');
        $siteFacebookName = settings::get('facebookName');

        $address1 = settings::get('address1');
        $address2 = settings::get('address2');
        $contactUsDesc = settings::get('contactUsDesc');

        $departments = \App\Models\Department::all();

        $header_og_img = settings::get('header_og_img');
        $chats = Chat::all();
        $header_img = settings::get('header_img');

        $centers = AccreditCenter::latest()->limit(4)->get();

        View::share(compact('siteDescription', 'siteLinked', 'siteLinkedName',
            'siteKeywords', 'whatsappNumber', 'contactEmail',
            'contactPhone', 'siteType', 'departments', 'siteInsta', 'siteFacebook',
            'siteFacebookName', 'siteInstaName', 'address1', 'address2', 'chats','centers', 'header_img', 'header_og_img', 'contactUsDesc'));
    }

    public function branches()
    {
        $branches = Branches::all()->groupBy('city');

        return view('front.branches', compact('branches'));
    }

    public function centers()
    {
        $centers = AccreditCenter::all();

        return view('front.centers', compact('centers'));
    }

    public function showCourse($course)
    {
        $course = Courses::where('slug', $course)->firstOrFail();
        $course->load('department');
        return view('front.course', compact('course'));
    }

    public function contactUs()
    {
        return view('front.contact');
    }

    public function aboutUs()
    {
        $aboutUs = settings::get('aboutUs');
        return view('front.about', compact('aboutUs'));
    }

    public function index()
    {

        $newses = News::latest()->limit(3)->get();
        $courses = \App\Models\Courses::with('department')->latest()->limit(5)->get();
        $upcomingCourses = \App\Models\Courses::upcoming()->get();
        $locations = \App\Models\Courses::select(DB::raw('DISTINCT location'))->get();
        return view('front.home', compact('courses', 'upcomingCourses', 'newses', 'locations'));

    }


    public function showDep($department)
    {

        $department = Department::where('slug', $department)->with('courses_all')->firstOrFail();
        $courses = $department->courses_all()->paginate();

        return view('front.department', compact('department', 'courses'));
    }

    public function search(Request $request)
    {


        $courses = Courses::query();
        if ($request->has('department') && $request->get('department') != 'null') {
            $courses->where('dep_id', $request->get('department'));
        }
        if ($request->has('location') && $request->get('location') != 'null') {
            $courses->where('location', $request->get('location'));
        }
        if ($request->has('month') && $request->get('month') != 'null') {
            $courses->whereMonth('start_date', $request->get('month'));

        }
        if ($request->has('all') && $request->get('all') != 'null') {

            //$courses->where('location',$request->get('location'));
        }

        if ($request->has('name') && $request->get('name') != 'null') {
            $courses->where('name', 'like', "%" . $request->get('name') . "%");
        }


//        $courses->getRelation('department');
        // dd($courses->with('department')->get());
        $result = $courses->with('department')->get();
        return view('front.search', compact('result'));
    }

    function instructors(Request $request)
    {
        // $instructors = Instructor::where('status', 'CERTIFIED')->get();
        $response = Http::get('https://portal.knowhowacademya.uk/api/getTrainers');
//        $response = Http::get('http://127.0.0.1:8001/api/getTrainers/');
        if ($response->status() == 404) {
            return redirect()->route('home');
        }
        $instructors = $response->object();

        return view('front.instructors.instructors', compact('instructors'));
    }

    function instructorsShow(Request $request, Instructor $instructor)
    {
//        if ($instructor->status != 'CERTIFIED') {
//            return redirect()->route('instructors');
//        }

        $response = Http::get('https://portal.knowhowacademya.uk/api/getTrainer/' . $instructor->id);
//        $response = Http::get('http://127.0.0.1:8001/api/getTrainer/' . $instructor->id);

        if ($response->status() == 404) {
            return redirect()->route('instructors');
        }
        $instructor = $response->object();
        return view('front.instructors.show', compact('instructor'));
    }

    public function submitContactUs(Request $request)
    {


        $this->validate($request, [
            'name' => 'required|string',
            'email' => 'required|email',
            'subject' => 'required|string',
            'message' => 'required|string',
        ]);


//        Mail::to($request->get('email'))
//            ->send(new ContactUs(['name' => $request->get('name')]));


        $to = 'Knowhowacademya@gmail.com';
        if ($contactUsEmail = settings::get('contactUsEmail')) {
            $to = $contactUsEmail;
        }

        Mail::to($to)
            ->send(new ContactUsAdmin([
                'name' => $request->get('name'),
                'email' => $request->get('email'),
                'subject' => $request->get('subject'),
                'msg' => $request->get('message'),
            ]));


        return redirect()->back()->with('success', 'Your message has been sent. Thank you!');
    }

    public function news()
    {
        $newses = News::paginate();
        return view('front.news.index', compact('newses'));
    }

    public function newsShow($news)
    {
        $news = News::where('id', $news)->firstOrFail();
        return view('front.news.show', compact('news'));
    }


    public function certificate_verify($uuid = null)
    {
        $certificate = Certificate::where('uuid', $uuid)->first();

        return view('front.certificate.info', compact('certificate'));
    }

    public function certificate_show($uuid = null)
    {
        $certificate = Certificate::where('uuid', $uuid)->first();
        if (!$certificate || !$certificate->file) {
            return redirect()->route('home');
        }

        return view('front.certificate.show', compact('certificate'));
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreNewsRequest;
use App\Http\Requests\UpdateNewsRequest;
use App\Models\News;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $newses = News::paginate();
        return  view('dashboard.news.index',compact('newses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return  view('dashboard.news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreNewsRequest $request)
    {

        $news = News::create([
            'title' => $request->title,
            'slug' => Str::slug($request->title,'-'),
            'body' => $request->get('content'),
        ]);


        if($request->hasFile('cover')){
            $file = $this->store_file([
                'source'=>$request['cover'],
                'validation'=>"image",
                'path_to_save'=>'/uploads/news/',
                'type'=>'IMAGE',
                'user_id'=>Auth::user()->id,
                //'resize'=>[500,1000],
                'small_path'=>'small/',
                'visibility'=>'PUBLIC',
                'file_system_type'=>env('FILESYSTEM_DRIVER','public'),
                'optimize'=>false
            ])['filename'];
            $news->update([
                'cover' => $file,
            ]);
        }

        return redirect()->route('news.index')->with('success','News added Successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news)
    {

        return  view('dashboard.news.edit',compact('news'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateNewsRequest $request, News $news)
    {
        $news->update([
            'title' => $request->title,
            'body' => $request->get('content'),
        ]);

        if($request->hasFile('cover')){
            if(Storage::disk('public')->exists("/public/uploads/news/" . $news->getAttributes()['cover'])){

                $file = Storage::disk('public')->delete("/public/uploads/news/" . $news->getAttributes()['cover']);

            }
            $file = $this->store_file([
                'source'=>$request['cover'],
                'validation'=>"image",
                'path_to_save'=>'/uploads/news/',
                'type'=>'IMAGE',
                'user_id'=>Auth::user()->id,
                //'resize'=>[500,1000],
                'small_path'=>'small/',
                'visibility'=>'PUBLIC',
                'file_system_type'=>env('FILESYSTEM_DRIVER','public'),
                'optimize'=>false
            ])['filename'];
            $news->update([
                'cover' => $file,
            ]);
        }


        return redirect()->route('news.index')->with('success','News Updated Successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(News $news)
    {
        if(Storage::disk('public')->exists("/public/uploads/news/" . $news->getAttributes()['cover'])){

            $file = Storage::disk('public')->delete("/public/uploads/news/" . $news->getAttributes()['cover']);

        }
        $news->delete();
        return redirect()->route('news.index')->with('success','News Deleted Successfully');

    }
}

resources/views/front/news/NewsItem.blade.php
<article class="overflow-hidden rounded-lg shadow transition hover:shadow-lg news-item">
    <img src="{{$news->cover}}" alt="{{$news->title}}" class="h-56 w-full object-fill" style="    object-fit: fill;    height: 14rem;    width: 100%;">

    <div class="bg-white p-4 sm:p-6">
        <time datetime="{{$news->created_at}}" class="block text-xs text-gray-500" style="font-size: .75rem;
    line-height: 1rem;">
           {{$news->created_at->diffForHumans()}}
        </time>

        <a href="{{route('front.news.show',$news->id)}}">
            <h3 class="mt-0.5 text-lg text-gray-900 news-title" style="    font-size: 1.125rem;
    line-height: 1.75rem;
}">
                {{$news->title}}
            </h3>
        </a>

        <p class="mt-2 text-sm leading-relaxed text-gray-500 line-clamp-3" style="-webkit-line-clamp: 3;">
            {{$news->short_title}}
        </p>
    </div>
</article>

resources/views/front/news/index.blade.php
@extends('layouts.front')

@section('title', 'News')

@section('content')

    @include('front.shared.nav',['class'=>''])
    <section class="intro-single">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-12">
                    <div class="title-single-box">
                        <h1 class="title-single text-center">News</h1>

                    </div>
                </div>

            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <div class="row gy-4">
                @foreach($newses as $news)
                    <div class="col-lg-4">
                        @include('front.news.NewsItem',['news'=>$news])
                    </div>
{{--                    <div class="col-lg-4">--}}
{{--                        <div class="position-relative mb-3 border  news-border">--}}
{{--                            <img src="{{$news->cover}}" alt="{{$news->title}}" height="250" class=" w-100"--}}
{{--                                 style="object-fit:cover;">--}}
{{--                            <div class="bg-white p-4">--}}
{{--                                <div class="mb-2">--}}

{{--                                    <a class="text-body" href="{{route('front.news.show',$news->slug)}}">--}}
{{--                                        <small>{{$news->created_at->diffForHumans()}}</small>--}}

{{--                                    </a>--}}
{{--                                </div>--}}
{{--                                <a class="h4 d-block mb-3 text-uppercase font-weight-bold news-title"--}}
{{--                                   href="{{route('front.news.show',$news->slug)}}">{{$news->title}}</a>--}}
{{--                                <p class="m-0">--}}
{{--                                    {{$news->short_title}}--}}

{{--                                </p>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                    </div>--}}
                @endforeach

                @if(!$newses)
                    <p>There is no News</p>
                    @endif
            </div>

            {{$newses->links()}}
        </div>
    </section>

    @include('front.shared.footer')
@endsection


@push('seo')

    <meta name="description" content="Know How News">
    <meta property="og:description"
          content="Know How News"/>

    <meta property="og:image" content="{{asset('img/header-img.webp')}}"/>

@endpush
@push('scripts')
    <script>
        $('.news-item').matchHeight();
    </script>
@endpush

resources/views/front/news/show.blade.php
@extends('layouts.front')

@section('title', 'News')

@section('content')

    @include('front.shared.nav',['class'=>''])
    <section class="intro-single">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-12">
                    <div class="title-single-box">
                        <h1 class="title-single text-center">News</h1>

                    </div>
                </div>

            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <div class="row">

                <div class="col-lg-12">
                    <!-- Trending Tittle -->
                    <div class="about-right mb-90">
                        <div class="news-cover img-fluid text-center">
                            <img class="img-fluid" src="{{$news->cover}}" alt="">
                        </div>
                        <div class=" heading-news mb-30 pt-30 text-center ">
                            <h3>{{$news->title}}</h3>
                        </div>
                        <div class="about-prea overflow-hidden">
                            {!!$news->body  !!}
                        </div>


                    </div>

                    @include('front.shared.share',['title'=>$news->title])
                </div>

            </div>

        </div>
    </section>

    @include('front.shared.footer')
@endsection

@push('seo')

    <meta name="description" content="{{$news->short_title}}"/>
    <meta property="og:description" content="{{$news->short_title}}"/>
    <meta property="og:image" content="{{$news->cover}}"/>

@endpush